
CREATE TABLE `user` 
( `id` INT(20) NOT NULL AUTO_INCREMENT , 
`name` VARCHAR(40) NOT NULL , 
`password` VARCHAR(40) NOT NULL , 
`email` VARCHAR(50) NOT NULL , 
PRIMARY KEY (`id`)) ENGINE = InnoDB;




